config/routes.rb
# These routes make up what will be found under /cms
# There are other routes that will be added at the root of the site (i.e. /) which can
#   be found in lib/cms/route_extensions.rb
Cms::Engine.routes.draw do
  get 'fakemap', to: 'section_nodes#fake'
  get '/content/:id/edit', :to => "content#edit", :as => 'edit_content'
  get '/dashboard', :to => "dashboard#index", :as => 'dashboard'
  get '/', :to => 'home#index', :as => 'home'
  get '/sitemap', :to => "section_nodes#index", :as => 'sitemap'
  get '/content_library', :to => "html_blocks#index", :as => 'content_library'
  get '/administration', :to => "users#index", :as => 'administration'

  devise_for :cms_users,
             skip: [:sessions],
             path: :users,
             class_name: 'Cms::PersistentUser',
             controllers: {passwords: 'cms/passwords'},
             module: :devise

  devise_scope :cms_user do
    get '/login' => "sessions#new", :as => 'login'
    get '/login' => "sessions#new", :as => :new_cms_user_session
    post '/login' => "sessions#create", :as => :cms_user_session
    get '/logout' => "sessions#destroy", :as => 'logout'

  end

  get '/toolbar', :to => "toolbar#index", :as => 'toolbar'

  put "/inline_content/:id", to: "inline_content#update", as: "update_inline_content"
  resources :page_components
  resources :connectors do
    member do
      put :move_up
      put :move_down
      put :move_to_bottom
      put :move_to_top
    end
  end
  resources :links

  resources :content_types, only: [] do
    collection do
      post :index
    end
  end
  resources :pages do
    member do
      put :archive
      put :hide
      put :publish
      get :versions
    end
    collection do
      put :publish
    end
    resources :tasks
  end
  get '/pages/:id/preview', to: 'content#preview', as: 'preview_page'
  get '/pages/:id/version/:version', :to => 'pages#version', :as => 'version_page'
  put '/pages/:id/revert_to/:version', :to => 'pages#revert_to', :as => 'revert_page'
  resources :tasks do
    member do
      put :complete
    end
    collection do
      put :complete
    end
  end
  resources :sections do
    resources :links, :pages
  end

  resources :section_nodes do
    member do
      put :move_to_position
    end
  end

  resources :attachments, :only => [:show, :create, :destroy]

  content_blocks :html_blocks
  content_blocks :forms
  resources :form_fields do
    member do
      get :confirm_delete
    end
  end
  post "form_fields/:id/insert_at/:position" => 'form_fields#insert_at'
  get "/forms/:id/fields/preview" => 'form_fields#preview', as: 'preview_form_field'

  resources :form_entries do
    collection do
      post :submit
    end
  end
  put "/form_entries" => "form_entries#bulk_update"
  # Faux nested resource for forms (not sure if #content_blocks allows for it.)
  get 'forms/:id/entries' => 'form_entries#index', as: 'entries'

  content_blocks :portlets
  post '/portlet/:id/:handler', :to => "portlet#execute_handler", :as => "portlet_handler"

  content_blocks :file_blocks
  content_blocks :image_blocks
  content_blocks :category_types
  content_blocks :categories
  content_blocks :tags

  get 'user' => "user#show", as: :current_user
  resources :users, except: :show do
    member do
      get :change_password
      patch :update_password
      put :disable
      put :enable
    end
  end
  resources :email_messages
  resources :groups
  resources :redirects
  resources :page_partials, :controller => 'dynamic_views'
  resources :page_templates, :controller => 'dynamic_views'
  resources :page_routes, except: :show do
    resources :conditions, :controller => "page_route_conditions"
    resources :requirements, :controller => "page_route_requirements"
  end
  get 'cache', :to => 'cache#show', :as => 'cache'
  delete 'cache', :to => 'cache#destroy'

  get "/routes", :to => "routes#index", :as => 'routes'

  add_routes_for_addressable_content_blocks
end

app/models/cms/abstract_file_block.rb
module Cms
  class AbstractFileBlock < ActiveRecord::Base
    self.table_name = "cms_file_blocks"

    def self.with_parent_id(parent_id)
      if parent_id == 'all'
        where(true) # Empty scope for chaining
      else
        self.includes({:attachments => :section_node})
            .references(:section_node)
            .where(["#{"cms_section_nodes"}.ancestry = ?",  Section.find(parent_id).ancestry_path])

      end
    end

    validates_presence_of :name

    # Return the parent section for this block.
    # @return [Cms::Section]
    def parent
      file.parent
    end

    # Exists here so FileBrowser can polymorphically call file_size on Page, Images, Files, etc.
    def file_size
      file.size.round_bytes
    end

    def path
      file.url
    end

    def self.publishable?
      true
    end

    def set_attachment_path
      if @attachment_file_path && @attachment_file_path != attachment.file_path
        attachment.file_path = @attachment_file_path
      end
    end

    def set_attachment_section
      if @attachment_section_id && @attachment_section_id != attachment.section
        attachment.section_id = @attachment_section_id
      end
    end

  end
end

app/models/cms/attachment.rb
module Cms
  class Attachment < ActiveRecord::Base

    MULTIPLE = 'multiple'

    SANITIZATION_REGEXES = [[/\s/, '_'], [/[&+()]/, '-'], [/[=?!'"{}\[\]#<>%]/, '']]
    #' this tic cleans up emacs ruby mode

    self.table_name = :cms_attachments

    cattr_accessor :definitions, :instance_writer => false
    @@definitions = {}.with_indifferent_access
    cattr_reader :configuration

    before_validation :set_cardinality
    before_save :set_section, :sanitized_file_path_and_name
    before_create :setup_attachment

    belongs_to :attachable, :polymorphic => true

    extend DefaultAccessible

    validates :attachment_name, :attachable_type, :presence => true

    is_addressable
    include Cms::Concerns::Addressable::DeprecatedPageAccessors

    is_archivable; is_publishable; uses_soft_delete; is_userstamped; is_versioned

    scope :named, lambda { |name|
      {:conditions => {:attachment_name => name.to_s}}
    }

    scope :multiple, -> {where(:cardinality => MULTIPLE)}

    FILE_BLOCKS = "Cms::AbstractFileBlock"
    validates_presence_of :data_file_path, :if => Proc.new { |a| a.attachable_type == FILE_BLOCKS }
    validates_uniqueness_of :data_file_path, :message =>"must be unique. (Another file, image or page is already using '%{value}').", :if => Proc.new { |a| a.attachable_type == FILE_BLOCKS }

    class << self

      def permitted_params
        super + [:attachable_class, :data]
      end
      # Makes file paths more URL friendly
      def sanitize_file_path(file_path)
        SANITIZATION_REGEXES.inject(file_path.to_s) do |s, (regex, replace)|
          s.gsub(regex, replace)
        end
      end

      def definitions_for(klass, type)
        definitions[klass].inject({}) { |d, (k, v)| d[k.capitalize] = v if v["type"] == type; d }
      end

      def configuration
        @@configuration ||= Cms::Attachments.configuration
      end

      # Returns a Proc that can be used to dynamically determine styles based on the Cms::Attachment class
      #
      # Paperclip can handle a :styles parameter which responds to :call(Paperclip::Attachment)
      def dynamically_return_styles
        lambda do |paperclip_attachment|
          cms_attachment = paperclip_attachment.instance

          # Look up the style for the given block
          if cms_attachment.has_assigned_content_type?
            configuration_value(cms_attachment.content_block_class, cms_attachment.attachment_name, :styles)
          else # New attachments that aren't associated with an Attaching type yet have no styles
            {}
          end
        end
      end

      def find_live_by_file_path(path)
        Attachment.published.not_archived.find_by_data_file_path path
      end


      def configure_paperclip
        # @todo This might be better done using subclasses of Attachment for each document instance.
        # We could use single table inheritance to avoid needing to do meta configurations.
        has_attached_file :data,
                          :url => configuration.url,
                          :path => configuration.path,
                          :styles => dynamically_return_styles,

                          # Needed for versioning so that we keep all previous files.
                          :preserve_files => true,

                          #TODO: enable custom processors
                          :processors => configuration.processors,
                          :default_url => configuration.default_url,
                          :default_style => configuration.default_style,
                          :use_timestamp => configuration.use_timestamp,
                          :whiny => configuration.whiny,
                          :storage => rail_config(:storage),
                          :s3_credentials => rail_config(:s3_credentials),
                          :bucket => rail_config(:s3_bucket),
                          :s3_host_name => rail_config(:s3_host_name),
                          :s3_host_alias => rail_config(:s3_host_alias)

      end

      # Looks up a value from Rails config
      def rail_config(key)
        Rails.configuration.cms.attachments[key]
      end

      # Looks up the configuration value given:
      # @param [Class] block_class The class of a block which has an attachment.
      # @param [String] name_of_attachment The name of the attachment association (i.e. if was 'has_attachment :photos' then pass 'photo')
      # @param [Symbol] key The key for the value to be fetched (i.e. :styles)
      def configuration_value(block_class, name_of_attachment, key)
        class_definitions = definitions[block_class]
        if class_definitions == nil
          raise "Couldn't find any definitions for '#{block_class}'. Available definitions are #{definitions.inspect}."
        end
        attachment_definition = class_definitions[name_of_attachment]
        if attachment_definition == nil
          raise "Verify that '#{block_class}' defines an attachment named ':#{name_of_attachment}'."
        end
        attachment_definition[key] || configuration.send(key)
      end

    end

    def attachable_class
      attachable_type
    end

    # @todo There isn't any good reason I know of why this needs to be a distinct field. Needed to add it to get it working for 4.0 though.
    def attachable_class=(klass)
      self.attachable_type = klass
    end

    def section=(section)
      dirty! if self.section != section
      super(section)
    end

    def config_value_for(key)
      self.class.configuration_value(content_block_class, attachment_name, key)
    end

    def content_block_class
      attachable.try(:class).try(:name) || attachable_type
      #attachable_class || attachable.try(:class).try(:name) || attachable_type
    end

    def icon
      {
          :doc => %w[doc],
          :gif => %w[gif jpg jpeg png tiff bmp],
          :htm => %w[htm html],
          :pdf => %w[pdf],
          :ppt => %w[ppt],
          :swf => %w[swf],
          :txt => %w[txt],
          :xls => %w[xls],
          :xml => %w[xml],
          :zip => %w[zip rar tar gz tgz]
      }.each do |icon, extensions|
        return icon if extensions.include?(data_file_extension)
      end
      :file
    end

    # For authorized users, return the path to get the specific version of the file associated with this attachment.
    # Guests should always get 'data_file_path' which is the public version of the asset.
    def attachment_version_path
      "/cms/attachments/#{id}?version=#{version}"
    end

    def public?
      section ? section.public? : false
    end

    def is_image?
      %w[jpg gif png jpeg].include?(data_file_extension)
    end

    # Returns a Paperclip generated relative path to the file (with thumbnail sizing)
    def url(style_name = configuration.default_style)
      data.url(style_name)
    end

    # Returns the absolute file location of the underlying asset
    def path(style_name = configuration.default_style)
      data.path(style_name)
    end

    def original_filename
      data_file_name
    end

    alias :file_name :original_filename

    def size
      data_file_size
    end

    def content_type
      data_content_type
    end

    alias :file_type :content_type

    # Returns the definitions for this particular attachment type.
    # @return [Hash] Empty Hash if no definition have been defined for this attachment.
    def config
      content_defs = definitions[content_block_class] ? definitions[content_block_class] : {}
      content_defs[attachment_name] ? content_defs[attachment_name] : {}
    end

    # Determines if this Attachment has access to configuration information yet. Until it is assigned to an Attaching object,
    # it will lack style information.
    def has_assigned_content_type?()
      attachable_type && attachment_name
    end

    protected

    private

    def data_file_extension
      data_file_name.split('.').last.downcase if data_file_name && data_file_name['.']
    end

    # Filter - Ensure that paths are going to URL friendly (and won't need encoding for special characters.')
    def sanitized_file_path_and_name
      if data_file_path
        self.data_file_path = self.class.sanitize_file_path(data_file_path)
        if !data_file_path.empty? && !data_file_path.starts_with?("/")
          self.data_file_path = "/#{data_file_path}"
        end
      end

      if data_file_name
        self.data_file_name = self.class.sanitize_file_path(data_file_name)
      end
    end

    def set_section
      unless parent
        self.parent = Section.root.first
      end
    end

    def setup_attachment
      data.instance_variable_set :@url, config_value_for(:url)
      data.instance_variable_set :@path, config_value_for(:path)
      data.instance_variable_set :@styles, config_value_for(:styles)
      data.instance_variable_set :@normalized_styles, nil
      data.send :post_process_styles
    end

    # Attachments should always be configured with a cardinality
    def set_cardinality
      unless cardinality
        self.cardinality = config[:type].to_s
      end

    end
  end
end

app/models/cms/category.rb
module Cms
  class Category < ActiveRecord::Base
    belongs_to :category_type, :class_name => 'Cms::CategoryType'
    belongs_to :parent, :class_name => 'Cms::Category'
    has_many :children, :class_name => 'Cms::Category', :foreign_key => "parent_id"
    is_searchable
    has_content_type :module => :categorization

    extend DefaultAccessible
    include Concerns::IgnoresPublishing

    validates_presence_of :category_type_id, :name
    validates_uniqueness_of :name, :scope => :category_type_id

    class << self
      def named(name)
        where(["#{table_name}.name = ?", name])
      end

      def of_type(type_name)
        where(["#{CategoryType.table_name}.name = ?", type_name])
        .order("#{Category.table_name}.name")
        .includes(:category_type)
        .references(:category_type)
      end
    end
    scope :top_level, -> { where(["#{Category.table_name}.parent_id is null"]) }
    scope :list, -> { includes(:category_type) }

    def ancestors
      fn = lambda do |cat, parents|
        if cat.parent_id
          p = self.class.find(cat.parent)
          fn.call(p, (parents << p))
        else
          parents.reverse
        end
      end
      fn.call(self, [])
    end

    def path(sep=" > ")
      (ancestors.map(&:name) + [name]).join(sep)
    end

    def category_type_name
      category_type ? category_type.name : nil
    end

    def self.columns_for_index
      [{:label => "Name", :method => :name, :order => "#{Category.table_name}.name"},
       {:label => "Type", :method => :category_type_name, :order => "#{CategoryType.table_name}.name"},
       {:label => "Updated On", :method => :updated_on_string, :order => "#{Category.table_name}.updated_at"}]
    end
  end
end

app/models/cms/category_type.rb
module Cms
  class CategoryType < ActiveRecord::Base

    has_many :categories, :class_name => 'Cms::Category'
    validates_presence_of :name
    validates_uniqueness_of :name
    is_searchable
    has_content_type :module => :categorization

    include Concerns::IgnoresPublishing

    def self.named(name)
      where(name: name)
    end

    # Return a map when the key is category type id as a string
    # and the value is an array of arrays, each entry having
    # the first value as the category path and the second value
    # being the category id as a string
    def self.category_map
      all.inject(Hash.new([])) do |map, ct|
        map[ct.id.to_s] = ct.category_list.map { |c| [c.path, c.id.to_s] }
        map
      end
    end

    # This is used to get the full list of categories for this category type in the correct order.
    def category_list(order="name")
      list = []
      fn = lambda do |cat|
        list << cat
        cat.children.order(order).each { |c| fn.call(c) }
      end
      categories.top_level.order(order).each { |cat| fn.call(cat) }
      list
    end

    def cannot_be_deleted_message
      categories.count.zero? ? nil : "This cannot be deleted because it is in use in #{categories.count} #{"category".pluralize_unless_one(categories.count)}"
    end

  end
end

app/models/cms/email_message_mailer.rb
module Cms
  class EmailMessageMailer < ActionMailer::Base


    def email_message(message)
      email = {:to=>message.recipients, :from=>message.sender, :subject => message.subject, :body =>message.body}
      email[:content_type]  = message.content_type if message.content_type
      mail email
    end

  end
end

app/views/layouts/cms/_content_types.html.erb
<ul class="dropdown-menu" id="<%= id %>">
  <% if library %>
    <%= nav_link_to "Text", cms.content_library_path %>
    <%= divider_tag %>
  <% end %>
  <% modules = Cms::ContentType.available_by_module
     modules.keys.sort.each_with_index do |module_name, i| %>
      <%= divider_tag(i) %>
      <% modules[module_name].each do |type| %>
          <%= nav_link_to h(type.display_name), engine_aware_path(type) %>
      <% end -%>
  <% end %>
</ul>

app/views/layouts/cms/_footer.erb
<div id="footer">
  <p>&copy; 1998-<%= Time.now.year %> <%= link_to "BrowserMedia", "http://www.browsermedia.com" %>. All Rights Reserved</p>
  <p><%= link_to "BrowserCMS", "http://www.browsercms.org" %> v<%= Cms.version %> | Rails <%= Rails.version %> | Env <%= Rails.env %></p>
</div>

app/views/layouts/cms/_head.html.erb
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<title><%= page_title %></title>
<%= stylesheet_link_tag 'cms/application' %>
<link href='http://fonts.googleapis.com/css?family=Roboto:400,100,300,100italic,300italic,400italic,500,500italic,700italic,700,900italic,900' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,600,700,800,300' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900,200italic,300italic,400italic,600italic,700italic,900italic' rel='stylesheet' type='text/css'>
<%= csrf_meta_tags %>
<%= yield :html_head %>

app/views/layouts/cms/_main_menu.html.erb
<div class="logged-in">
  <div class="container center-column">
    <ul class="subnav right">
      <li><%= link_to current_user.full_name, cms.edit_user_path(current_user) unless current_user.guest? %></li>
      <li><%= link_to "Settings", "#" unless current_user.guest? %></li>
      <li><%= link_to "Help", 'https://github.com/browsermedia/browsercms/wiki', target: '_blank' %></li>
      <li><%= link_to "Logout", cms.logout_path unless current_user.guest? %></li>
    </ul>
  </div>
</div>

<div class="primary-nav">
  <div class="container center-column">
    <%= link_to image_tag('cms/logo.png', class: 'main-logo'), "/" %>
    <ul class="mainnav">
      <% if current_user.able_to?(:edit_content) %>
      <li>
        <%= link_to "Dashboard", cms.dashboard_path %>
        <ul class="dropdown-menu">
        </ul>
      </li>
      <li>
        <%= link_to "Pages", cms.sitemap_path %>
      </li>
      <li>

        <a href="#"
           class="dropdown-toggle"
           data-toggle="dropdown">
          Assets
          <b class="caret"></b>
        </a>
        <%= render partial: 'layouts/cms/content_types', locals: { library: true, id: 'content-library-menu' } %>
      </li>
      <% end %>
      <% if current_user.able_to? :administrate %>
      <li>
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <%= nav_link_to "Users", cms.users_path %>
          <%= nav_link_to "Groups", cms.groups_path %>
          <%= divider_tag %>
          <%= nav_link_to "Partials", cms.page_partials_path %>
          <%= nav_link_to "Page Templates", cms.page_templates_path %>
          <%= divider_tag %>
          <%= nav_link_to "Redirects", cms.redirects_path %>
          <%= nav_link_to "Routes", cms.page_routes_path %>
          <%= nav_link_to "Page Cache", cms.cache_path %>
          <%= nav_link_to "Email Messages", cms.email_messages_path %>
          <% Rails.application.config.cms.tools_menu.each do |menu_item| %>
              <%= nav_link_to(menu_item[:name], self.send(menu_item[:engine]).send(menu_item[:route_name])) %>
          <% end %>
        </ul>
      </li>
      <% end %>
    </ul>

    <% if current_user.able_to?(:edit_content) %>
    <div class="btn-group">
      <%= menu_button "New", new_button_path, id: 'new-content-button', class: 'btn btn-primary', tabindex: '-1' %>
      <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown" tabindex="-1">
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu pull-right">
        <%= render 'cms/toolbar/new_pages_menu' %>
        <% modules = Cms::ContentType.available_by_module
           modules.keys.sort.each_with_index do |module_name, i| %>
            <%= divider_tag(i) %>
            <% modules[module_name].each do |type| %>
                <%= nav_link_to h(type.display_name), new_engine_aware_path(type), id: "create_new_#{type.param_key}" %>
            <% end -%>
        <% end %>
      </ul>

    </div>
    <% end %>
  </div>
</div>

app/views/layouts/cms/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= javascript_include_tag "cms/application" %>
  <%= javascript_include_tag cms_content_editor %>
  <%= render 'layouts/cms/head' %>
</head>
<body>
<nav id="main-nav">
  <%= render 'layouts/cms/main_menu' %>
</nav>
<%= render 'cms/sites/flash' %>
<section class="container center-column main-container bottom-form-btn clearfix">
  <% if content_for?(:before_main_content) %>
      <%= yield :before_main_content  %>
  <% end %>
  <%= yield %>
  <div class="padded row-fluid">
    <div class="span12"><%= render :partial => 'layouts/cms/footer' %></div>
  </div>
</section>
</body>
</html>

app/views/layouts/cms/content_page.html.erb
<%# Sub-layout
    Wraps a view so it will display in the :main container of a page without needing to call content_for(:main)
%>
<% content_for :main do %><%= yield %><% end %>
<%= render template: cms_template %>

app/views/layouts/cms/page_editor.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= javascript_include_tag 'cms/page_toolbar' %>
  <%= render 'layouts/cms/head' %>
  <%= stylesheet_link_tag 'cms/page_editor' %>
</head>
<body>
<nav id="main-nav">
  <%= render 'layouts/cms/main_menu' %>
</nav>
<div id="submenu">
  <div class="container center-column">
    <% if !@page.live? %>
        <span class="status draft" id="page-status-label">This page is in draft status</span>
    <% else %>
        <span class="status published" id="page-status-label">Published</span>
    <% end %>
    <%= render 'add_content_modal' %>
    <span class="last-saved">Last saved: &nbsp;<strong><%= format_date(@page.updated_at) %></strong></span>

    <%= link_to "Publish",
                engine(@page).polymorphic_path([:publish, @page]),
                class: "right btn btn-small btn-primary primary-cta http_put",
                :id => "publish_button",
                :target => "_top",
                :enabled => !(!current_user.able_to?(:publish_content) || !current_user.able_to_edit?(@page) || @page.version != @page.draft.version || @page.live?)
    %>

    <div class="btn-group">
      <% if @page.respond_to?(:current_task) %>
          <% unless @page.current_task %>
              <%= link_to "Assign",
                          cms.new_page_task_path(@page),
                          :id => "assign_button",
                          :target => "_top",
                          :align => 'none',
                          class: 'btn btn-small',
                          :enabled => !(@page.assigned_to == current_user || !current_user.able_to_edit?(@page))
              %>
          <% else %>
              <%= link_to "Complete Task",
                          cms.complete_task_path(@page.current_task),
                          :id => "complete_task_button",
                          class: 'http_put btn btn-small',
                          :target => "_top",
                          :enabled => !(@page.assigned_to != current_user || !current_user.able_to_edit?(@page)) %>
          <% end %>
      <% end %>
      <%= link_to "Versions",
                  engine(@page).polymorphic_path([:versions, @page]),
                  :target => "_top",
                  class: "btn btn-small",
                  :enabled => current_user.able_to_edit?(@page)
      %>
    </div>

    <div class='btn-group'>
      <%= able_to? :publish_content do %>
          <%= link_to "Delete",
                      engine_aware_path(@page),
                      :id => "delete_button",
                      title: "Are you sure you want to delete '#{@page.name}'?",
                      :target => "_top",
                      :enabled => current_user.able_to_publish?(@page),
                      class: 'btn btn-small btn-danger http_delete confirm_with_title' %>
      <% end %>
    </div>
    <%= render 'mobile_toolbar' %>

    <div class="btn-group right">
      <%= link_to "Configure",
                  edit_engine_aware_path(@page),
                  class: "btn btn-small",
                  :id => "edit_properties_button",
                  :target => "_top",
                  :enabled => current_user.able_to_edit?(@page)
      %>
      <%= link_to "Preview", preview_content_path(@page), id: "preview_button", class: 'btn btn-small', target: "_blank" if @page.class.addressable?  %>

    </div>

    <%= yield :page_buttons if content_for?(:page_buttons) %>

  </div>
</div>
<%= render 'cms/sites/flash' %>
<%= yield %>
</body>
</html>